version: "3.9"

services:
  app:
    image: spring-boot-terraform-example-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./logs:/app/logs